# Railway will auto-detect the Dockerfile and deploy accordingly
# This file provides optional configuration

[build]
# Railway will automatically use the Dockerfile in the root directory

[deploy]
# Restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Health check (optional - Railway has defaults)
healthcheckPath = "/"
healthcheckTimeout = 300
