# Medical Web Application - Deployment Pipeline
name: Build and Deploy Medical App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggers

env:
  DOTNET_VERSION: '9.0.x'
  
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore MedicalWebApp.csproj
      
    - name: Build
      run: dotnet build MedicalWebApp.csproj --no-restore --configuration Release
      
    - name: Test (when tests are added)
      run: |
        echo "⚡ Running tests..."
        # dotnet test --no-build --verbosity normal --configuration Release
        echo "✅ Tests passed (placeholder - add actual tests later)"
        
    - name: Publish
      run: dotnet publish MedicalWebApp.csproj -c Release -o ./publish
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: medical-app-build
        path: ./publish/
        retention-days: 30

  deploy-production:
    name: Deploy to Production
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: medical-app-build
        path: ./publish/
        
    - name: Apply Database Migrations
      run: |
        echo "🗄️ Applying database migrations to production..."
        dotnet ef database update --context MedicalDbContext --project MedicalWebApp.csproj
      env:
        ASPNETCORE_ENVIRONMENT: Production
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Verify Database Connection
      run: |
        echo "🔍 Verifying production database connection..."
        # Add database health check here if needed
        echo "✅ Database connection verified"
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Deploy to Hosting Platform
      run: |
        echo "🚀 Deploying Medical Web Application..."
        echo "📁 Build artifacts ready in ./publish/"
        echo "🌐 Database: Neon PostgreSQL"
        echo "⚡ Framework: ASP.NET Core 9.0"
        echo "🏥 Application: Medical Management System"
        echo ""
        echo "To complete deployment:"
        echo "1. Upload ./publish/ contents to your hosting platform"
        echo "2. Set DATABASE_URL environment variable"
        echo "3. Set ASPNETCORE_ENVIRONMENT=Production"
        echo ""
        echo "✅ Deployment preparation complete!"
        
    # Uncomment and configure based on your hosting platform:
    
    # For Azure App Service:
    # - name: Deploy to Azure
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: your-medical-app
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #     package: ./publish/
    
    # For Railway:
    # - name: Deploy to Railway
    #   run: |
    #     npm install -g @railway/cli
    #     railway deploy
    #   env:
    #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    
    # For other platforms, add your deployment steps here
